### ISSUE TITLE
ENH: execute named variables eagerly in interactive environment

### ISSUE THREAD

**Issue by UranusSeven** [xprobe-inc/xorbits#162]
### Is your feature request related to a problem? Please describe
In interactive environment, users tend to do exploratory analysis and there's no so called "final result". Thus, deferred execution may cause duplicated execution. In the following example, line 0 and line 1 are executed twice:

```python
[0]: df = pd.DataFrame({"foo": (1, 2, 3), "bar": (4, 5, 6)})
[1]: df["baz"] = df["bar"] + 3
[2]: df.sum(axis=0)
[3]: df.describe()
```

### Describe the solution you'd like
Execute named variables eagerly in interactive env.

**Comment by UranusSeven** [comment]
Here's my plan:

1. if the env is interactive, save the top frame (ipython input frame) when xorbits being imported.
2. whenever a tileable being executed, for each other tileables in the tileable graph
    2.1 if the tileable is defined in the top frame (has a name), execute it
    2.2 ignore it

**Comment by aresnow1** [comment]
> Here's my plan:
> 
> 1. if the env is interactive, save the top frame (ipython input frame) when xorbits being imported.
> 2. whenever a tileable being executed, for each other tileables in the tileable graph
>    2.1 if the tileable is defined in the top frame (has a name), execute it
>    2.2 ignore it

About 1, what does `save the top frame` mean, store them as global variables?

About2, when in an interactive environment, we should collect all Xorbits objects and execute them whenever execution is triggered.

**Comment by UranusSeven** [comment]
After talking with @aresnow1 , we both agree that binding a frame to a variable has side effects (like GC). And there's a better way to find Xorbits objects defined by a user:
```
get_ipython().user_ns
```
