### ISSUE TITLE
DOC：Requirements for README in Chinese

### ISSUE THREAD

**Issue by Nliver** [xprobe-inc/xorbits#226]
### Is your feature request related to a problem? Please describe

Well，I think this will make it easier for Chinese speakers to understand what Xorbits is doing~

### Describe the solution you'd like

Maybe I can translate it, but, uh, maybe the authorities are preparing it? Who knows ~

**Comment by qianduoduo0904** [comment]
Yeah, thank you for your issue, when had a mirror: https://gitee.com/xprobe-inc/xorbits

We want to keep the internationalization of original Xorbits. 

Thank you anyway, I will close this issue, and welcome to submit others.
