### ISSUE TITLE
BUG: runtime error caused by `read_xxx` with relative path

### ISSUE THREAD

**Issue by UranusSeven** [xprobe-inc/xorbits#271]
### Describe the bug
In the interactive environment, the work dir of a local cluster is determined during initialization. If the current dir of IPython changed, loading a dataframe with a relative path may result in a FileNotFound error.

### To Reproduce
```python
In [1]: import xorbits

In [2]: xorbits.init()
2023-03-14 21:20:14,070 xorbits._mars.deploy.oscar.local 22259 WARNING  Web service started at http://0.0.0.0:45351

In [3]: cd /path/to/my/dataset

In [4]: import xorbits.pandas as pd

In [5]: trips = pd.read_parquet("data.parquet")  # will cause a FileNotFoundError since Xorbits is initalized under another directory

In [6]: trips 
```

### Expected behavior
Xorbits should better take the relative path and make it an absolute path.

**Comment by aa452948257** [comment]
Take
