### ISSUE TITLE
ENH: implement `np.tri`

### ISSUE THREAD

**Issue by UranusSeven** [xprobe-inc/xorbits#277]
### Is your feature request related to a problem? Please describe
`np.tri` is a wildly used function. It is basicly a combination of `np.ones` and `np.tril` and should be easy to implement.

Check this out for how to implement a mars operand: https://docs.pymars.org/en/latest/development/operand.html

And the impl of `ones` may be a good example: https://github.com/xprobe-inc/xorbits/blob/main/python/xorbits/_mars/tensor/datasource/ones.py

**Comment by qianduoduo0904** [comment]
np.tril and np.triu is implemented already, maybe np.tri is just a wrapper?

**Comment by aa452948257** [comment]
take.
