### ISSUE TITLE
ENH: lazy init pandas fallbacks

### ISSUE THREAD

**Issue by UranusSeven** [xprobe-inc/xorbits#304]
### Is your feature request related to a problem? Please describe
To reduce the import time, we can init pandas fallback methods when users actually need them.

You can refer to the impl of [numpy fallbacks](https://github.com/xprobe-inc/xorbits/blob/0ad7c68d5517c2368653652ea14971a9dd2f6613/python/xorbits/numpy/random/__init__.py#L38).

You should also init pandas fallbacks when `__dir__` being called.

**Comment by jiayini1119** [comment]
Take
