### ISSUE TITLE
TST: doc build optimization

### ISSUE THREAD

**Issue by UranusSeven** [xprobe-inc/xorbits#390]
Note that the issue tracker is NOT the place for general support.  For
discussions about development, questions about usage, or any general questions,
contact us on https://discuss.xorbits.io/.

We build docs using readthedocs for each PR right now. But the concurrency is quite limited so the CI is frequently blocked.

A better way could be using a github action to check if a PR is gonna break docs. For example, https://github.com/marketplace/actions/sphinx-build.

**Comment by aresnow1** [comment]
Closed by #463
