### ISSUE TITLE
DOC: Add more documentation about custom configuration. 

### ISSUE THREAD

**Issue by aresnow1** [xprobe-inc/xorbits#454]
Users can specify custom configuration using `-f` option when deploy Xorbits, there should be some examples to show users how to override default options.

**Comment by shark-21** [comment]
Hey , can you reference the page where you want to address this issue. I think it the [cluster deployment page](https://doc.xorbits.io/en/latest/user_guide/deployment_cluster.html). Also can you give some example parameters which can be shown in the example using -f flag.

**Comment by shark-21** [comment]
take

**Comment by aresnow1** [comment]
> Hey , can you reference the page where you want to address this issue. I think it the [cluster deployment page](https://doc.xorbits.io/en/latest/user_guide/deployment_cluster.html). Also can you give some example parameters which can be shown in the example using -f flag.

The example mainly guides users on how to override the [default configuration](https://github.com/xprobe-inc/xorbits/blob/main/python/xorbits/_mars/deploy/oscar/base_config.yml). If users want to modify default `node_timeout` and `transfer_block_size`, specify `-f your-config.yml` when using command line, and yaml file looks like this:
```
"@inherits": @default
storage:
  default_config: 
    transfer_block_size: 10 * 1024 ** 2
cluster:
  node_timeout: 1200
```

**Comment by luweizheng** [comment]
Maybe we should add a new page in this folder: https://github.com/xprobe-inc/xorbits/tree/main/doc/source/user_guide
As there are so many parameters that users can customize. All users of Kubernetes, cloud, or cluster can customize depending on their needs.
@aresnow1

**Comment by aresnow1** [comment]
> Maybe we should add a new page in this folder: https://github.com/xprobe-inc/xorbits/tree/main/doc/source/user_guide As there are so many parameters that users can customize. All users of Kubernetes, cloud, or cluster can customize depending on their needs. @aresnow1

Sure, this may require a slightly larger workload. For now, we can first add an example of a custom config file as in #508.

**Comment by luweizheng** [comment]
> Sure, this may require a slightly larger workload. For now, we can first add an example of a custom config file as in #508.

It really needs a lot of effort. I think maintainers can add a new page and move this example into this new page. Other contributors can add their content later.
