### ISSUE TITLE
BUG: Unable to Build Docker Image for Xorbits Development Environment: Dockerfile Not Found

### ISSUE THREAD

**Issue by YELineee** [xprobe-inc/xorbits#461]
### Describe the bug

When setting up the environment, following the code on the [[Creating a development environment — Xorbits 0.1.2 ](https://doc.xorbits.cn/development/contributing_environment.html#step-3-build-and-install-xorbits)] encountered a problem with option 3: using Docker in step 2. The command provided, "docker build -t xorbits-dev ." , seems problematic, as it does not fail to find the Docker file. According to Docker's official documentation, Dockerfile files are stored in subdirectories and the source files cannot be found when compiling.

```
docker build -t xorbits-dev .

[+] Building 0.0s (2/2) FINISHED
 => [internal] load .dockerignore                                                         0.0s
 => => transferring context: 213B                                                         0.0s
 => [internal] load build definition from Dockerfile                                      0.0s
 => => transferring dockerfile: 2B                                                        0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount968795007/Dockerfile: no such file or directory
```

### To Reproduce

To help us to reproduce this bug, please provide information below:

1. Your Python version

   - Python 3.11.3

2. The version of Xorbits you use

   -  latest

3. Versions of crucial packages, such as numpy, scipy and pandas

   - 1.5.3

4. Full stack of the error.

5. Minimized code to reproduce the error.

   ~~~
   # Build the image
   docker build -t xorbits-dev .
   ~~~

   

### Expected behavior

- Successfully built

**Comment by ChengjieLi28** [comment]
Hi, @YELineee . 
- If you simply want a complete environment with xorbits, you can directly pull the corresponding image from our Dockerhub repository.
Ref: https://hub.docker.com/repository/docker/xprobe/xorbits/general

- If you indeed need to manually build a Docker image, for example, to add some additional Python libraries, you can follow these steps:
Make sure your working directory is at the top-level "xorbits" directory, then execute the following command
```bash
$ docker build -t xprobe/xorbits:dev --progress=plain -f python/xorbits/deploy/docker/Dockerfile  . --build-arg PYTHON_VERSION=<your_python_version>
```
Replace ``<your_python_version>`` with the Python version you need. Currently, we support versions 3.8, 3.9, 3.10, and 3.11.

There are indeed errors in our documentation, and I will promptly submit a pull request to make the necessary modifications.
