### ISSUE TITLE
BUG: xorbits.pd.set_options got Attribute Error

### ISSUE THREAD

**Issue by Zhou1213CN** [xprobe-inc/xorbits#471]
### To Reproduce
To help us to reproduce this bug, please provide information below:

```
import xorbits.pandas as pd

pd.set_option('display.max_rows', None)
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 pd.set_option('display.max_rows', None)

File ~/Desktop/xorbits/python/xorbits/pandas/__init__.py:65, in __getattr__(name)
     63     return unimplemented_func
     64 else:
---> 65     raise AttributeError(name)

AttributeError: set_option

**Comment by qianduoduo0904** [comment]
Another user encounters the same error, we can support the display part, it works only for the client.
