### ISSUE TITLE
DOC: supported python version

### ISSUE THREAD

**Issue by UranusSeven** [xprobe-inc/xorbits#500]
https://doc.xorbits.io/en/latest/getting_started/installation.html

Since we have dropped py 3.7, the doc should be updated as well.

**Comment by shark-21** [comment]
take

**Comment by shark-21** [comment]
![image](https://github.com/xprobe-inc/xorbits/assets/95162887/b7b2bb06-cded-46c6-b947-a97e3f52024c)
what should be done here?

**Comment by UranusSeven** [comment]
> ![image](https://github.com/xprobe-inc/xorbits/assets/95162887/b7b2bb06-cded-46c6-b947-a97e3f52024c)
> 
> what should be done here? 
> 
> As it the requirements given are for python versions < 3.8 but they are not used anymore. So should I delete the message in parenthesis or should I leave it as it is.

Good catch! I think we could remove them.
