### ISSUE TITLE
BUG: incorrect GPU usage scale 

### ISSUE THREAD

**Issue by UranusSeven** [xprobe-inc/xorbits#510]
### Describe the bug
![image](https://github.com/xprobe-inc/xorbits/assets/109661872/0e2551ee-54b6-47d3-bca2-dd032a265900)

Usage should not exceed total. Looks like the scale of GPU usage is incorrect.

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version
2. The version of Xorbits you use
master
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
5. Minimized code to reproduce the error.
Run:
```bash
python ./benchmarks/tpch/run_queries.py --data_set /path/to/tpch-sf1 --gpu --cuda_devices 0
```
Open the web UI and you should see the abnormal GPU usage.

### Expected behavior
The usage should always be less than 1.0 (total).

**Comment by RayJi01** [comment]
take
